// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherNews.Persistence.Context;

namespace WeatherNews.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210827021416_Inicial1")]
    partial class Inicial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherNews.Domain.Models.Citysweather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("NameCity")
                        .IsRequired()
                        .HasColumnType("varchar(225)");

                    b.HasKey("Id");

                    b.ToTable("Citiessweather");
                });
#pragma warning restore 612, 618
        }
    }
}
